### ISSUE TITLE
Buttons need re-worked

### ISSUE THREAD

**Issue by arthvadrr** [arthvadrr/pomo-me#3]
Buttons aren't properly showing CSS hover, focus, active styles. Additionally, the buttons for the timer aren't properly displaying what is going on with the current state of the timer. May have to apply classes based on timer state to get the buttons to work properly. Might be a little more work to get this to work correctly, but not difficult.

**Comment by sebuelias** [comment]
Can I take this up? Can you provide me with a little guidance?

**Comment by arthvadrr** [comment]
@sebuelias Go for it. Its a small project so feel free to experiment if needed. The styles are in src/sass and being compiled to build/styles.min.css. I was thinking that the actual way the buttons work probably need re-worked (I need a state machine, but that's a separate issue). 

The buttons should always show a hover and active state no matter what application state is.
Button styles should match

**Comment by sebuelias** [comment]
@javabryan 
![image](https://user-images.githubusercontent.com/10326494/119232643-914ede00-bb43-11eb-887c-d37f56027ca9.png)

This error shows up when I try ```npm start```
And suggested fixes online isn't solving the issue.

Sorry to be a bother, but I am new and if this is some issue, I can raise as an issue
If not, can you please let me know?

**Comment by arthvadrr** [comment]
EOL
